<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="377015" started-at="2012-12-06T23:44:59Z" finished-at="2012-12-06T23:51:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="377015" started-at="2012-12-06T23:44:59Z" finished-at="2012-12-06T23:51:16Z">
      <class name="pack_test.TestCount">
        <test-method status="PASS" signature="befTest()[pri:0, instance:pack_test.TestCount@3476a7]" name="befTest" is-config="true" duration-ms="15" started-at="2012-12-07T02:44:59Z" finished-at="2012-12-07T02:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befTest -->
        <test-method status="FAIL" signature="TestStart()[pri:0, instance:pack_test.TestCount@3476a7]" name="TestStart" duration-ms="362703" started-at="2012-12-07T02:44:59Z" finished-at="2012-12-07T02:51:02Z">
          <exception class="pack_utils.ExceptFailTest">
            <full-stacktrace>
              <![CDATA[Тест провален, причина Значение счетчика "Все статусы" 2 не равно количеству отображаемых объявлений 1.
	at pack_page.Page_IrrPrivateOffice.CheckCountAndVisibleAdvert(Page_IrrPrivateOffice.java:337)
	at pack_test.TestCount.TestStart(TestCount.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- pack_utils.ExceptFailTest -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestStart -->
        <test-method status="PASS" signature="aftTest()[pri:0, instance:pack_test.TestCount@3476a7]" name="aftTest" is-config="true" duration-ms="15" started-at="2012-12-07T02:51:16Z" finished-at="2012-12-07T02:51:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftTest -->
      </class> <!-- pack_test.TestCount -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
